#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - find-latest-version                  Copyright(c) 2019 cPanel, L.L.C.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package ea_rubygem_sqlite3::find_latest_version;

use strict;
use warnings;

use HTML::TreeBuilder::XPath ();

use FindBin;
use lib "../ea-tools/lib/ea4_tool";    # assumes ea-tools is checked out next to this repo
use ea4_tool::util ();

ea4_tool::util::find_latest_version( \&_get_required, \&_add_sum ) if !caller();

###############
#### helpers ##
###############

sub _get_required {
    my ($http) = @_;

    my $res = $http->get("https://rubygems.org/gems/sqlite3/versions?page=2");
    if ( !$res->{success} ) {
        die "Could not GET ruby gem info from https://rubygems.org/gems/sqlite3\n";
    }

    my $dom      = HTML::TreeBuilder::XPath->new_from_content( $res->{content} );
    my $node_set = $dom->findnodes('//a');
    my @nodes    = $node_set->get_nodelist();

    my $version;
    foreach my $node (@nodes) {
        my $href = $node->attr('href');
        if ( $href && $href =~ m{^/gems/sqlite3/versions/(1\.4\.\d+)$} ) {
            my $this_version = $1;
            if ( !$version ) {

                # the first one listed is the correct one
                $version = $this_version;
            }
        }
    }

    die "Could not determine version\n" if !$version;

    my $name = "sqlite3-${version}.gem";
    my $url  = "http://rubygems.org/gems/$name";

    return ( $version, $url, $name );
}

sub _add_sum {
    my ( $http, $hr ) = @_;

    # can not get old SHAa

    return 1;
}
